version: '3.7'
services:
  web:
    image: nginx:latest
    container_name: web
    ports:
      - "8080:80"
    networks:
      - app_network

  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: toor
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
