   # Usar nginx:alpine como base
   FROM nginx:alpine

   # Copiar el archivo index.html al directorio de contenido de nginx
   COPY index.html /usr/share/nginx/html/

   # Exponer el puerto 80
   EXPOSE 80
