# Usar la imagen base de Python
FROM python:3.9

# Establecer el directorio de trabajo en el contenedor
WORKDIR /usr/src/app

# Copiar el script al contenedor
COPY app.py .

# Establecer el comando principal
ENTRYPOINT ["python", "app.py"]
