version: '3.9'

services:

  youtrack:
    image: "jetbrains/youtrack:${YOUTRACK_VERSION}"
    container_name: youtrack
    hostname: youtrack
    user: 13001:13001 # Limitación usuarios no root
    restart: unless-stopped
#    read-only: true # Sólo lectura

    mem_limit: 2g  # Limita la memoria RAM a 2GB
    cpus: 1.5  # Limita el uso de CPU a 1.5 núcleos

    # Reducción de privilegios del kernel
    cap_drop:
      - ALL  # Elimina todas las capacidades del kernel que no son necesarias

    ports:
      - "${YOUTRACK_PORT}:8080"
    expose:
      - 8080
    volumes:
      - "${DATA_PATH}/youtrack/data:/opt/youtrack/data"
      - "${DATA_PATH}/youtrack/conf:/opt/youtrack/conf"
      - "${DATA_PATH}/youtrack/logs:/opt/youtrack/logs"
      - "${DATA_PATH}/youtrack/backups:/opt/youtrack/backups"
    deploy:
      placement:
        constraints:
          - node.labels.youtrack.data == true
    #networks:
    #  - proxy
    #labels:
      #  - traefik.enable=true
      #  - traefik.docker.network=proxy
      #  - traefik.http.routers.youtrack.rule=Host(`projects.example.com`)
      #  - traefik.http.services.youtrack.loadbalancer.server.port=8080
      #  # Part for local lan services only; disable to expose externally
      #  - traefik.http.routers.youtrack.middlewares=local-ipwhitelist@file

#networks:
#  proxy:
#    external: true
